version: '3'

services:
  db:
    container_name: ai-saas-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ai-saas
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    container_name: ai-saas-adminer
    image: adminer
    ports:
      - 8080:8080

  webhooks:
    container_name: ai-saas-webhooks
    image: deltaprojects/smee-client
    ports:
      - 3000:3000
    command: smee -u https://smee.io/0BYa0HCYlkLL1UIo -P '/api/webhooks'
